on:
    issues:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: 'Auto-assign issue'
              uses: ./
              with:
                  assignees: octocat,nguyengiabk
                  numOfAssignee: 1
